# Use an official Node runtime as the parent image
FROM node:14 as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build -- --prod

# Use Nginx to serve the application
FROM nginx:alpine

# Copy the build output to replace the default nginx contents
COPY --from=build /app/dist/angular-dashboard /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]