# Etapa 1: Configurar o ambiente com Node.js
FROM node:18 AS base

WORKDIR /app

# Copiar arquivos de dependências
COPY package*.json ./

# Instalar dependências do projeto
RUN npm install

# Instalar Angular CLI globalmente
RUN npm install -g @angular/cli

# Copiar o código fonte para dentro do container
COPY . .

# Etapa 2: Produção
FROM base AS production

# Construir a aplicação Angular
RUN npm run build --prod

# Usar Nginx para servir a aplicação Angular
FROM nginx:alpine

# Copiar configuração personalizada do Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar os arquivos do build para o Nginx
COPY --from=production /app/dist/new-frontend /usr/share/nginx/html

# Expor a porta padrão do Nginx
EXPOSE 80

# Iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]

# Etapa 3: Desenvolvimento
FROM base AS development

# Expor a porta para o servidor de desenvolvimento
EXPOSE 4200

# Iniciar o servidor de desenvolvimento Angular
CMD ["npm", "run", "start"]
