version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: dxpert-db-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DXPERT_BANCO
    ports:
      - "3333:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: dxpert-api/Dockerfile
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/src
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;User Id=root;Password=root;Database=DXPERT_BANCO
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./new-frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ./new-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data_dev:

networks:
  app-network:
    driver: bridge
