@echo off
echo Limpar cache do NPM...
npm cache clean --force

echo Excluir node_modules e package-lock.json...
rmdir /s /q node_modules
del /f /q package-lock.json

echo Atualizar Angular CLI globalmente...
npm install -g @angular/cli

echo Atualizar Angular CLI localmente...
call ng update @angular/cli

echo Atualizar Angular Core...
call ng update @angular/core

echo Atualizar pacotes restantes...
call npm outdated

echo Reinstalar pacotes...
npm install

echo Verificar problemas de compatibilidade...
call ng lint

echo Testar aplicativo...
call ng serve
